#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
name: MOODLE_33PLUS - Releasing in the Plugins directory

on:
  push:
    branches:
      - MOODLE_33PLUS
    paths:
      - 'version.php'

jobs:
  workflow_group_35_plus_release:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/group-35-plus-release.yml@main
    with:
      plugin_name: auth_userkey
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
